// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/[restaurantSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/[restaurantSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/billing">> = Specific
  const handler = {} as typeof import("../../src/app/owner/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/owner/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/login">> = Specific
  const handler = {} as typeof import("../../src/app/owner/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/menu">> = Specific
  const handler = {} as typeof import("../../src/app/owner/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/accounting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/accounting">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/accounting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/orders">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/tables/[tableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/tables/[tableId]">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/tables/[tableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/operations/tables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/operations/tables">> = Specific
  const handler = {} as typeof import("../../src/app/owner/operations/tables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/settings">> = Specific
  const handler = {} as typeof import("../../src/app/owner/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
